swagger: "2.0"
info:
  version: "0.0.1"
  title: Blockchain Insurance Api

# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /contractfactory/createEarthQuakeContract:
    # binds a127 app logic to a route
    x-swagger-router-controller: creation_controller
    post:
      tags: 
        - insurer
      description: " "
      # used as the method name of the controller
      operationId: create
      parameters:
        - name: createRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/createRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/createResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /contractfactory/getEarthQuakeContract:
    # binds a127 app logic to a route
    x-swagger-router-controller: info_controller
    post:
      tags:
        - info
      description: " "
      # used as the method name of the controller
      operationId: getEQContract
      parameters:
        - name: getEQContractRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/getEQContractRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/getEQContractResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/getCollateral:
    # binds a127 app logic to a route
    x-swagger-router-controller: info_controller
    post:
      tags:
        - info
      description: " "
      # used as the method name of the controller
      operationId: getCollateral
      parameters:
        - name: getCollateralRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/getCollateralRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/getCollateralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eth/getAllAccounts:
    post:
      tags: 
        - info
      description: "Gibt alle account adresse zurück"
      operationId: "getAllAccounts"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/accountSchema"          
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "info_controller"
  /eqcontract/getCosts:
    # binds a127 app logic to a route
    x-swagger-router-controller: info_controller
    post:
      tags:
        - info
      description: " "
      # used as the method name of the controller
      operationId: getCosts
      parameters:
        - name: getCostsRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/getCostsRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/getCostsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/requestInsurance:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - customer
      description: " "
      # used as the method name of the controller
      operationId: requestInsurance
      parameters:
        - name: requestInsuranceRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/requestInsuranceRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/confirmInsurance:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - customer
      description: " "
      # used as the method name of the controller
      operationId: confirm
      parameters:
        - name: confirmRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/confirmRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/triggerInsurance:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - customer
      description: " "
      # used as the method name of the controller
      operationId: trigger
      parameters:
        - name: triggerRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/triggerRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/triggerRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/acceptInsurance:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - insurer
      description: " "
      # used as the method name of the controller
      operationId: accept
      parameters:
        - name: acceptRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/acceptRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/lockCollateral:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - insurer
      description: " "
      # used as the method name of the controller
      operationId: lockCollateral
      parameters:
        - name: lockCollateralRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/lockCollateralRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /eqcontract/closeInsurance:
    # binds a127 app logic to a route
    x-swagger-router-controller: insurance_controller
    post:
      tags:
        - insurer
      description: " "
      # used as the method name of the controller
      operationId: close
      parameters:
        - name: closeRequest
          in: body
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/closeRequest"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/closeResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

            


# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  createRequest:
    properties:
      address:
        type: string
  createResponse:
    properties:
      address:
        type: string
  getEQContractResponse:
    properties:
      address:
        type: string
  requestInsuranceRequest:
    properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
      strength:
        type: number
      geolocation:
        type: string
      value:
        type: number
      duration:
        type: number
  confirmRequest:
   properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
      ether:
        type: number
  triggerRequest:
    properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
  triggerRespone:
    properties:
      ether:
        type: number
  acceptRequest:
    properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
      costs:
        type: number
  lockCollateralRequest:
    properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
      ether:
        type: number
  closeResponse:
    properties:
      ether:  
        type: number
  closeRequest:
    properties:
      yourAddress:
        type: string
      eqcontract:
        type: string
  getEQContractRequest:
    properties:
      id:
        type: number
  getCollateralRequest:
    properties:
      eqcontract:
        type: string
  getCollateralResponse:
    properties:
      collateral:
        type: number
  getCostsRequest:
    properties:
      eqcontract:
        type: string  
  getCostsResponse:
    properties:
      costs:
        type: number
  accountSchema:
    properties:
      accounts:
        type: array
        items:
          type: string
      
        
  

    
  
